# Generated by Django 3.1.5 on 2021-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0003_auto_20210224_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='id',
        ),
        migrations.AddField(
            model_name='shape',
            name='shape_id',
            field=models.CharField(default='km', max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
