# Generated by Django 3.1.5 on 2021-02-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0004_auto_20210224_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shape',
        ),
    ]
