# Generated by Django 3.1.5 on 2021-04-08 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0007_auto_20210401_1256'),
    ]

    operations = [

        migrations.CreateModel(
            name='EvacuationPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('vehicles_available', models.IntegerField()),
            ],
        ),
    ]
